spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false

application:
  host: http://localhost:8080
  files:
    image:
      uri: ${application.host}/api/files/img/
    dir: src/main/resources/static
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
